//
//  Header.h
//  58DaijiaClient
//  宏定义
//  Created by huangbin on 14-4-3.
//  Copyright (c) 2014年 58. All rights reserved.
//

#ifndef _8DaijiaClient_Header_h
#define _8DaijiaClient_Header_h
#define IsIOS7 ([[[[UIDevice currentDevice] systemVersion] substringToIndex:1] intValue]>=7)


#define FontSize(value) [UIFont systemFontOfSize:value]
#define HexToUIColorRGB(value) [UIColor colorWithRed:((value&0xFF0000)>>16)/255.0 green:((value&0xFF00)>>8)/255.0 blue:(value&0xFF)/255.0 alpha:1.0]

#define RESEND_INTERVAL 180
#define MARGIN_TOP 12.0f
#define MARGIN_LEFT 12.f
#define SPACING 12.0f
#define DRIVER_LIST_PHOTO_HEIGHT  136/2.0f
#define DRIVER_LIST_PHOTO_WIDTH  DRIVER_LIST_PHOTO_HEIGHT

#define DRIVER_LIST_PHONE_HEIGHT 100/2.0f
#define DRIVER_LIST_PHONE_WIDTH DRIVER_LIST_PHONE_HEIGHT

#define ORDER_STATE_CELL_HEIGHT 84/2.0f
#define ORDER_CONTENT_FINISH_CELL_HEIGHT 360/2.0f
#define ORDER_CONTENT_CELL_HEIGHT 304/2.0f
#define ORDER_STATE_MARGIN_TOP (ORDER_STATE_CELL_HEIGHT - 60/2)/2.0f

//发送订单列别请求时列表每页个数
#define DJ_PAGE_SIZE 10

//通用上边距
#define COMMON_TOPSPACE 5
//标题或姓名字体大小
#define TITLE_FONT_SIZE 18.0
//标签字体大小
#define LABEL_FONT_SIZE 13.0

//司机列表cell的高度
#define DRIVER_CELL_HEIGHT (MARGIN_TOP*2 + DRIVER_LIST_PHOTO_HEIGHT)
//司机列表中Imageview距离cell左边边框的左边距,相当于CGRect的x值
#define DRIVER_IMAGE_LEFTSPACE 5
//司机列表中Imageview距离cell顶部的上边距，相当于CGRect的y值
#define DRIVER_IMAGE_TOPSPACE (COMMON_TOPSPACE)
//司机列表中Imageview距离cell顶部的下边距，与上边距相等
#define DRIVER_IMAGE_BUTTOMSPACE (DRIVER_IMAGE_TOPSPACE)
//司机列表cell中头像的宽度，相当于CGRect的width值
#define DRIVER_IMAGE_WIDTH 80
//司机列表cell中头像的高度，相当于CGRect的height值 固定为cell高度-2倍上边距
#define DRIVER_IMAGE_HEIGHT (DRIVER_CELL_HEIGHT - 2*DRIVER_IMAGE_TOPSPACE)
//司机列表cell中imageView的X结束值
#define DRIVER_IMAGE_X_END (DRIVER_IMAGE_LEFTSPACE + DRIVER_IMAGE_WIDTH)
//司机列表cell中imageView的y结束值
#define DRIVER_IMAGE_Y_END (DRIVER_IMAGE_TOPSPACE + DRIVER_IMAGE_HEIGHT)

//每个label的通用高度
#define LABEL_COMMON_HEIGHT ((DRIVER_CELL_HEIGHT - 4*COMMON_TOPSPACE)/3.0)

//司机列表cell中 司机姓名与头像的空白距离
#define DRIVER_NAME_LABEL_SPACE 10
//司机列表cell中 司机姓名label的x值
#define DRIVER_NAME_LABEL_X (DRIVER_IMAGE_X_END + DRIVER_NAME_LABEL_SPACE)
//司机列表cell中 司机姓名label的y值 ,设置与头像上对齐
#define DRIVER_NAME_LABEL_Y (DRIVER_IMAGE_TOPSPACE)
//司机列表cell中 司机姓名label的宽度
#define DRIVER_NAME_LABEL_WIDTH 60
//司机列表cell中 司机姓名label的高度
#define DRIVER_NAME_LABEL_HEIGHT (LABEL_COMMON_HEIGHT)
//司机列表cell中namelabel的x结束值
#define DRIVER_NAME_LABEL_X_END (DRIVER_NAME_LABEL_X + DRIVER_NAME_LABEL_WIDTH)
//司机列表cell中namelabel的y结束值
#define DRIVER_NAME_LABEL_Y_END (DRIVER_NAME_LABEL_Y + DRIVER_NAME_LABEL_HEIGHT)



//司机列表cell中 司机驾龄与司机姓名间隔
#define DRIVER_YEAR_LABEL_TOPSPACE (COMMON_TOPSPACE)
//司机列表cell中 司机驾龄X值 ,设置与司机姓名左对齐
#define DRIVER_YEAR_LABEL_X (DRIVER_NAME_LABEL_X)
//司机列表cell中 司机驾龄Y值
#define DRIVER_YEAR_LABEL_Y (DRIVER_NAME_LABEL_Y_END + DRIVER_YEAR_LABEL_TOPSPACE)
//司机列表cell中 司机驾龄标签宽度
#define DRIVER_YEAR_LABEL_WIDTH 75
//司机列表cell中 司机驾龄标签高度
#define DRIVER_YEAR_LABEL_HEIGHT (LABEL_COMMON_HEIGHT)
//司机列表cell中 司机驾龄标签的x结束值
#define DRIVER_YEAR_LABEL_X_END (DRIVER_YEAR_LABEL_X + DRIVER_YEAR_LABEL_WIDTH)
//司机列表cell中 司机驾龄标签的y结束值
#define DRIVER_YEAR_LABEL_Y_END (DRIVER_YEAR_LABEL_Y + DRIVER_YEAR_LABEL_HEIGHT)



//司机列表cell中 司机距离与司机驾龄间隔
#define DRIVER_DISTANCE_LABEL_TOPSPACE (COMMON_TOPSPACE)
//司机列表cell中 司机距离标签x值 ,设置与司机驾龄左对齐
#define DRIVER_DISTANCE_LABEL_X (DRIVER_YEAR_LABEL_X)
//司机列表cell中 司机距离标签y值
#define DRIVER_DISTANCE_LABEL_Y (DRIVER_YEAR_LABEL_Y_END + DRIVER_DISTANCE_LABEL_TOPSPACE)
//司机列表cell中 司机距离标签宽度 设置与司机驾龄同宽
#define DRIVER_DISTANCE_LABEL_WIDTH (DRIVER_YEAR_LABEL_WIDTH)
//司机列表cell中 司机距离标签高度 设置与司机驾龄同高
#define DRIVER_DISTANCE_LABEL_HEIGHT (DRIVER_YEAR_LABEL_HEIGHT)
//司机列表cell中 司机距离标签x结束值
#define DRIVER_DISTANCE_LABEL_X_END (DRIVER_DISTANCE_LABEL_X + DRIVER_DISTANCE_LABEL_WIDTH)
//司机列表cell中 司机距离标签y结束值
#define DRIVER_DISTANCE_LABEL_Y_END (DRIVER_DISTANCE_LABEL_Y + DRIVER_DISTANCE_LABEL_HEIGHT)


//司机列表cell中 司机籍贯与司机姓名间距
#define DRIVER_PROVINCE_SPACE 10
//司机列表cell中 司机籍贯标签X值
#define DRIVER_PROVINCE_LABEL_X (DRIVER_DISTANCE_LABEL_X_END + DRIVER_PROVINCE_SPACE)
//司机列表cell中 司机籍贯标签高度
#define DRIVER_PROVINCE_LABEL_HEIGHT (LABEL_COMMON_HEIGHT)
//司机列表cell中 司机籍贯标签宽度
#define DRIVER_PROVINCE_LABEL_WIDTH 60
//司机列表cell中 司机籍贯标签X结束值
#define DRIVER_PROVINCE_LABEL_X_END (DRIVER_PROVINCE_LABEL_X + DRIVER_PROVINCE_LABEL_WIDTH)
//司机列表cell中 司机籍贯标签Y值  与司机驾龄上对齐
#define DRIVER_PROVINCE_LABEL_Y (DRIVER_YEAR_LABEL_Y)
//司机列表cell中 司机籍贯标签Y值
#define DRIVER_PROVINCE_LABEL_Y_END (DRIVER_PROVINCE_LABEL_Y + DRIVER_PROVINCE_LABEL_HEIGHT)

//司机列表cell中 电话图标与籍贯间距
#define DRIVER_PHONE_IMAGE_SPACE 0
//司机列表cell中 电话图标高度
#define DRIVER_PHONE_IMAGE_HEIGHT 80
//司机列表cell中 电话图标高度
#define DRIVER_PHONE_IMAGE_WIDTH  70
//司机列表cell中 电话图标x值
#define DRIVER_PHONE_IMAGE_X (DRIVER_PROVINCE_LABEL_X_END + DRIVER_PHONE_IMAGE_SPACE)
//司机列表cell中 电话图标y值
#define DRIVER_PHONE_IMAGE_Y (COMMON_TOPSPACE)

//订单列表cell中 nameLabel的左边距
#define ORDER_NAME_LABEL_LEFTSPACE 5

//订单列表cell中 nameLabel的x值
#define ORDER_CONTENT_NAME_LABEL_X (ORDER_NAME_LABEL_LEFTSPACE + 7.5)
//订单列表cell中 nameLabel的y值
#define ORDER_CONTENT_NAME_LABEL_Y COMMON_TOPSPACE
//订单列表cell中 nameLabel的高度
#define ORDER_CONTENT_NAME_HEIGTH LABEL_COMMON_HEIGHT
//订单列表cell中 nameLabel的宽度
#define ORDER_CONTENT_NAME_WIDTH 45
//订单列表cell中 nameLabel的x结束值
#define ORDER_CONTENT_NAME_X_END (ORDER_CONTENT_NAME_LABEL_X + ORDER_CONTENT_NAME_WIDTH + 7.5)
//订单列表cell中 nameLabel的y结束值
#define ORDER_CONTENT_NAME_Y_END (ORDER_CONTENT_NAME_LABEL_Y + LABEL_COMMON_HEIGHT)

//订单列表cell中 冒号左右的间隔距离
#define ORDER_CONTENT_COMMA_COMMEN_SPACE 1

//订单列表cell中 司机姓名与冒号的空白距离
#define ORDER_CONTENT_COMMA_NAME_SPACE ORDER_CONTENT_COMMA_COMMEN_SPACE
//订单列表cell中 冒号的X值
#define ORDER_CONTENT_COMMA_X (ORDER_CONTENT_NAME_X_END + ORDER_CONTENT_COMMA_NAME_SPACE)
//订单列表cell中 冒号的Y值 设定与namelabel上对齐
#define ORDER_CONTENT_COMMA_Y ORDER_CONTENT_NAME_LABEL_Y
//订单列表cell中 冒号标签的高度
#define ORDER_CONTENT_COMMA_HEIGHT LABEL_COMMON_HEIGHT
//订单列表cell中 冒号标签的宽度
#define ORDER_CONTENT_COMMA_WIDTH 5
//订单列表cell中 COMMALabel的x结束值
#define ORDER_CONTENT_COMMA_X_END (ORDER_CONTENT_COMMA_X + ORDER_CONTENT_COMMA_WIDTH)
//订单列表cell中 COMMALabel的Y结束值
#define ORDER_CONTENT_COMMA_Y_END (ORDER_CONTENT_COMMA_Y + ORDER_CONTENT_COMMA_HEIGHT)

//订单列表cell中 司机姓名与冒号的空白距离
#define ORDER_CONTENT_PHONE_COMMA_SPACE ORDER_CONTENT_COMMA_COMMEN_SPACE
//订单列表cell中 电话的X值
#define ORDER_CONTENT_PHONE_X (ORDER_CONTENT_COMMA_X_END + ORDER_CONTENT_PHONE_COMMA_SPACE)
//订单列表cell中 电话的Y值 设定与namelabel上对齐
#define ORDER_CONTENT_PHONE_Y ORDER_CONTENT_NAME_LABEL_Y
//订单列表cell中 冒号标签的高度
#define ORDER_CONTENT_PHONE_HEIGHT LABEL_COMMON_HEIGHT
//订单列表cell中 冒号标签的宽度
#define ORDER_CONTENT_PHONE_WIDTH 90
//订单列表cell中 COMMALabel的x结束值
#define ORDER_CONTENT_PHONE_X_END (ORDER_CONTENT_PHONE_X + ORDER_CONTENT_PHONE_WIDTH)
//订单列表cell中 COMMALabel的Y结束值
#define ORDER_CONTENT_PHONE_Y_END (ORDER_CONTENT_PHONE_Y + ORDER_CONTENT_PHONE_HEIGHT)

//订单列表cell中 电话与开始位置的上下间隔
#define ORDER_CONTENT_PHONE_POSITION_TOPSPACE COMMON_TOPSPACE
//订单列表cell中 开始位置标签x值
#define ORDER_CONTENT_START_POSITION_X ORDER_NAME_LABEL_LEFTSPACE
//订单列表cell中 开始位置标签Y值
#define ORDER_CONTENT_START_POSITION_Y (ORDER_CONTENT_PHONE_Y_END + ORDER_CONTENT_PHONE_POSITION_TOPSPACE)
//订单列表cell中 开始位置标签高度
#define ORDER_CONTENT_START_POSITION_HEIGHT LABEL_COMMON_HEIGHT
//订单列表cell中 开始位置标签宽度
#define ORDER_CONTENT_START_POSITION_WEIGHT 55
//订单列表cell中 开始位置标签X结束值
#define ORDER_CONTENT_START_POSITION_X_END (ORDER_CONTENT_START_POSITION_X + ORDER_CONTENT_START_POSITION_WEIGHT)
//订单列表cell中 开始位置标签Y结束值
#define ORDER_CONTENT_START_POSITION_Y_END (ORDER_CONTENT_START_POSITION_Y + ORDER_CONTENT_START_POSITION_HEIGHT)

////订单列表cell中 电话与开始位置的上下间隔
//#define ORDER_CONTENT_PHONE_POSITION_TOPSPACE COMMON_TOPSPACE
//订单列表cell中 位置标签x值
#define ORDER_CONTENT_POSITION_X ORDER_CONTENT_PHONE_X
//订单列表cell中 位置标签Y值
#define ORDER_CONTENT_POSITION_Y ORDER_CONTENT_START_POSITION_Y
//订单列表cell中 位置标签高度
#define ORDER_CONTENT_POSITION_HEIGHT LABEL_COMMON_HEIGHT
//订单列表cell中 位置标签宽度
#define ORDER_CONTENT_POSITION_WEIGHT 360
//订单列表cell中 位置标签X结束值
#define ORDER_CONTENT_POSITION_X_END (ORDER_CONTENT_POSITION_X + ORDER_CONTENT_POSITION_WEIGHT)
//订单列表cell中 位置标签Y结束值
#define ORDER_CONTENT_POSITION_Y_END (ORDER_CONTENT_POSITION_Y + ORDER_CONTENT_POSITION_HEIGHT)


//订单列表cell中 金额与开始位置的上下间隔
#define ORDER_CONTENT_PRICE_POSITION_TOPSPACE COMMON_TOPSPACE
//订单列表cell中 金额标签的x值
#define ORDER_CONTENT_PRICE_TITLE_X ORDER_CONTENT_START_POSITION_X
//订单列表cell中 金额标签的Y值
#define ORDER_CONTENT_PRICE_TITLE_Y (ORDER_CONTENT_START_POSITION_Y_END + ORDER_CONTENT_PRICE_POSITION_TOPSPACE -10)
//订单列表cell中 金额标签的宽度
#define ORDER_CONTENT_PRICE_TITLE_WIDTH 55
//订单列表cell中 金额标签的高度
#define ORDER_CONTENT_PRICE_TITLE_HEIGHT LABEL_COMMON_HEIGHT
//订单列表cell中 金额标签的x结束值
#define ORDER_CONTENT_PRICE_TITLE_X_END (ORDER_CONTENT_PRICE_TITLE_X + ORDER_CONTENT_PRICE_TITLE_WIDTH)
//订单列表cell中 金额标签的Y结束值
#define ORDER_CONTENT_PRICE_TITLE_Y_END (ORDER_CONTENT_PRICE_TITLE_Y + ORDER_CONTENT_PRICE_TITLE_HEIGHT)

//订单列表cell中 价格标签x值
#define ORDER_CONTENT_PRICE_LABEL_X ORDER_CONTENT_POSITION_X
//订单列表cell中 价格标签Y值
#define ORDER_CONTENT_PRICE_LABEL_Y ORDER_CONTENT_PRICE_TITLE_Y
//订单列表cell中 价格标签高度
#define ORDER_CONTENT_PRICE_LABEL_HEIGHT LABEL_COMMON_HEIGHT
//订单列表cell中 价格标签宽度
#define ORDER_CONTENT_PRICE_LABEL_WIDTH 50


#define ORDER_CONTENT_COMMENT_BUTTON_X 250
#define ORDER_CONTENT_COMMENT_BUTTON_Y ORDER_CONTENT_PRICE_LABEL_Y
#define ORDER_CONTENT_COMMENT_BUTTON_WIDTH 50
#define ORDER_CONTENT_COMMENT_BUTTON_HEIGHT LABEL_COMMON_HEIGHT
//400热线号码
#define HOTLINE_NUM @"400-105-1003"
#endif
